default:
  http_metas:
    content-type:  text/html;  charset:utf-8
  metas:
    title:  hemsinif-sinif yoldaslarini dostlari tampaq ve onlarla elaqede olmaq ucun sosial sebeke
    robots:  index, follow
    description:   hemsinif-sinif yoldaslarini ve dostlari tampaq ve onlarla elaqede olmaq ucun sosial sebeke
    keywords:  hemsinif, sinif yoldaslari, dostlar, friends
    language: az, en, ru
  stylesheets:  [layout?ver=2]
  javascripts:  [jquery,jquery.hf.js?ver=2]
  has_layout:  on
  layout:  layout
